add docs and redo install() and run()

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,61 +1,115 @@
 #!/usr/bin/env bash
 
 # SPDX-License-Identifier: Apache-2.0
-
 # Source: https://github.com/loverdos/pre-commit
+# shellcheck disable=SC2034
+SCRIPT_ID=AF13AE47-34E0-41FA-8FF8-AF660A922C6A
+
+# Requirements: recent `bash`, `curl`, `git`, and some other general utilities.
+# On macOS the built-in `bash` may not work, so install from `brew`.
+# Tested-on: macOS, Linux
+# Tested-on: fish, bash
+
+# Manages the `git` pre-commit hook.
+# The script serves both as an installer for itself and a hook runner.
+#
+# To install, you need to be in a `git` working tree already, and run
+# the following from a `bash` shell.
+#
+#   bash <(curl -fsSL https://raw.githubusercontent.com/loverdos/pre-commit/main/pre-commit) --install
+#
+# If you are not using bash, you can just call it twice :)
+#
+#   bash -c "bash <(curl -fsSL https://raw.githubusercontent.com/loverdos/pre-commit/main/pre-commit) --install"
+#
+# This does the following:
+#   - Creates a `.pre-commit` folder in the repo, and places the current script there.
+#   - Makes sure that `.git/hooks/pre-commit` links to the above.
+#     A pre-existing `.git/hooks/pre-commit` is backed up in `.git/hooks`.
+#
+# In the `.pre-commit` folder you place the scripts to run before any `git commit`.
+# That's it.
+#
+# Developing the script itself:
+#   1. ... make changes
+#   2. `./install`
+#   3. `git commit`
+# We assume `shellcheck` is installed.
 
 set -euo pipefail
 
-# shellcheck disable=SC2034
-SCRIPT_ID=AF13AE47-34E0-41FA-8FF8-AF660A922C6A
+MY_URL=https://raw.githubusercontent.com/loverdos/pre-commit/main/pre-commit
+
+dot_pre_commit=.pre-commit
+dot_pre_commit_pre_commit=$dot_pre_commit/pre-commit
+dot_git_hooks=.git/hooks
+dot_git_hooks_pre_commit=$dot_git_hooks/pre-commit
 
 cmds=()
 cmd_statuses=()
 successes=0
 failures=0
-dot_pre_commit=.pre-commit
-git_root="" # to be filled in
+
+git_root="$(git rev-parse --show-toplevel 2>/dev/null)"
 
 function LOG() {
-    echo "$@" >&2
+    echo "== $*" >&2
 }
 
-function git-get-root() {
-    git rev-parse --show-toplevel 2>/dev/null
+function mk-id() {
+    echo "$(date -u +%F).$$.$RANDOM"
 }
 
 function install() {
-    cd "$git_root" || exit 1
+    LOG "git root is at: $git_root"
+    cd "$git_root"
 
-    mkdir -p .git/hooks
+    # Make sure all the needed folders are there
+    mkdir -p $dot_pre_commit
+    mkdir -p $dot_git_hooks
 
-    hook_path=".git/hooks/pre-commit"
+    # Get a fresh version of ourselves from the internet.
+    # (yeah, redundant the first time you install it but self-updates next time you call it with --install...)
+    # This will override any file already residing there.
+    curl -fsSL $MY_URL -o $dot_pre_commit_pre_commit
+    chmod +x $dot_pre_commit_pre_commit
 
-    cp "$0" $hook_path
-    chmod +x $hook_path
-    LOG "Installed pre-commit hook $0 to .git/hooks/pre-commit"
-
-    if [[ ! -d $dot_pre_commit ]]; then
-        mkdir -p $dot_pre_commit
-        LOG "Created $dot_pre_commit folder"
-
-        hook_00=$dot_pre_commit/00
-        cat >"$hook_00" <<EOF
-#!/usr/bin/env bash
-
-echo Success before committing
-EOF
-
-        chmod +x $hook_00
-        LOG "Wrote sample hook $hook_00"
+    if git ls-files --error-unmatch $dot_pre_commit_pre_commit >/dev/null 2>&1; then
+        # file is tracked
+        if ! git diff --quiet -- $dot_pre_commit_pre_commit; then
+            # ... and we just downloaded a new version
+            LOG "Installed a new version of: $dot_pre_commit_pre_commit"
+            LOG "To see what's new: git diff $dot_pre_commit_pre_commit"
+            LOG "To add it:         git add $dot_pre_commit_pre_commit"
+        fi
     else
-        LOG "$dot_pre_commit folder already exists, I am not touching anything."
+        LOG "Installed for the first time: $dot_pre_commit_pre_commit"
+        LOG "To add it: git add $dot_pre_commit_pre_commit"
     fi
+
+    ls -al $dot_pre_commit_pre_commit
+
+    # Set the pre-commit hook to link here, save any old version.
+    # cp $dot_pre_commit_pre_commit $dot_git_hooks_pre_commit
+    if [[ -f $dot_git_hooks_pre_commit || -L $dot_git_hooks_pre_commit ]]; then
+        suffix=$(mk-id)
+        new_location=$dot_git_hooks_pre_commit."$suffix"
+
+        LOG "$dot_git_hooks_pre_commit exists, moving to $new_location"
+
+        mv $dot_git_hooks_pre_commit "$new_location"
+    fi
+
+    ln -s "$git_root"/$dot_pre_commit_pre_commit $dot_git_hooks_pre_commit
+
+    LOG "Installed $dot_git_hooks_pre_commit"
+    ls -al $dot_git_hooks_pre_commit
+    LOG "You may want to see all your hooks: ls -al $dot_git_hooks"
 }
 
 function check_statuses() {
     LOG
-    LOG "== Results: $successes success(es), $failures failure(s)"
+    LOG "Results: $successes success(es), $failures failure(s)"
 
     result=0
     for i in "${!cmds[@]}"; do
@@ -67,17 +121,27 @@ function check_statuses() {
         fi
     done
 
+    LOG
+
     exit $result
 }
 
 function run() {
-    # Proceed with the pre-commit checks.
-    LOG "Running pre-commit hook(s)"
+    local mark=""
+
+    LOG "Running pre-commit hook(s) from $(pwd)"
     set +e
 
-    for hook in "$git_root/$dot_pre_commit"/*; do
+    cd "$git_root"
+
+    for hook in "$dot_pre_commit"/*; do
+        # We do not want to run ourselves recursively ...
+        if [[ "$hook" == "$dot_pre_commit_pre_commit" ]]; then
+            continue
+        fi
+
         LOG
-        LOG "== Run: $hook"
+        LOG "Run: $hook"
 
         $hook
 
@@ -87,11 +151,13 @@ function run() {
 
         if ((status == 0)); then
             ((successes++))
+            mark="✅"
         else
             ((failures++))
+            mark="❌"
         fi
 
-        LOG "== Exit: [$status]"
+        LOG "Exit: $mark [= $status] $hook"
     done
 
     set -e
@@ -99,8 +165,7 @@ function run() {
 }
 
 # We must always be in a git work tree.
-git_root=$(git-get-root)
-if [[ -z $git_root ]]; then
+if [[ -z "$git_root" ]]; then
     LOG "Error: not inside a Git repository"
     exit 1
 fi
